# **Assignment-10(Data Visualization - Numpy)**

## **NumPy**
NumPy is a Python library.

NumPy is used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy is short for "Numerical Python".

In [ ]:
pip install numpy

In [ ]:
# Create a NumPy array:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Checking NumPy Version


In [ ]:
import numpy as np

print(np.__version__)

1.25.2


## **NumPy Creating Arrays**



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


## Dimensions in Arrays


## 0-D Arrays


In [ ]:
# Create a 0-D array with value 42
import numpy as np

arr = np.array(42)
print(arr)

42


## 1-D Arrays


In [ ]:
# Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2-D Arrays


In [ ]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D arrays


In [ ]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Higher Dimensional Arrays


In [ ]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np

arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print("N.o of Dimensions:",arr.ndim)

[[[[[1 2 3 4 5]]]]]
N.o of Dimensions: 5


## **NumPy Array Indexing**
## Access Array Elements


In [ ]:
# Get the first element from the following array:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [ ]:
# Get the second element from the following array:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [ ]:
# Get third and fourth elements from the following array and add them.
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[2] + arr[3])

7


## Access 2-D Arrays


In [ ]:
# Access the element on the first row, second column:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element on 1st row :",arr[0,1])

2nd element on 1st row : 2


In [ ]:
# Access the element on the 2nd row, 5th column:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("5th element on 2nd row :",arr[1,4])

5th element on 2nd row : 10


## Access 3-D Arrays


In [ ]:
# Access the third element of the second array of the first array:
import numpy as np

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2])

6


## Negative Indexing


In [ ]:
# Print the last element from the 2nd dim:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Last element from 2nd dim: ",arr[1,-1])

Last element from 2nd dim:  10


## **NumPy Array Slicing**
## Slicing arrays


In [ ]:
# Slice elements from index 1 to index 5 from the following array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

[2 3 4 5]


In [ ]:
# Slice elements from index 4 to the end of the array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[4:])

[5 6 7 8]


In [ ]:
# Slice elements from the beginning to index 4 (not included):
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[:4])

[1 2 3 4]


## Negative Slicing


In [ ]:
# Slice from the index 3 from the end to index 1 from the end:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[-3:-1])

[6 7]


## STEP


In [ ]:
# Return every other element from index 1 to index 5:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5:2])

[2 4]


In [ ]:
# Return every other element from the entire array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
# From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## **NumPy Data Types**
## Checking the Data Type of an Array



In [ ]:
# Get the data type of an array object:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
# Get the data type of an array containing strings:
import numpy as np

arr = np.array(["apple","banana","cherry"])
print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type


In [ ]:
# Create an array with data type string:
import numpy as np

arr = np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


For i, u, f, S and U we can define size as well.

In [ ]:
# Create an array with data type 4 bytes integer:
import numpy as np

arr = np.array([1,2,3,4,5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


## Converting Data Type on Existing Arrays


In [ ]:
# Change data type from float to integer by using 'i' as parameter value:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Change data type from float to integer by using int as parameter value:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
# Change data type from integer to boolean:
import numpy as np

arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## **NumPy Array Copy vs View**

## COPY:


In [ ]:
# Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 50
print(arr)
print(x)

[50  2  3  4  5]
[1 2 3 4 5]


## VIEW:




In [ ]:
# Make a view, change the original array, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] =  50
print(arr)
print(x)

[50  2  3  4  5]
[50  2  3  4  5]


## Make Changes in the VIEW:


In [ ]:
# Make a view, change the view, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] =  30
print(arr)
print(x)

[30  2  3  4  5]
[30  2  3  4  5]


## Check if Array Owns its Data


In [ ]:
# Print the value of the base attribute to check if an array owns it's data or not:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## **NumPy Array Shape**


## Get the Shape of an Array


In [ ]:
# Print the shape of a 2-D array:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("Shape of Array:",arr.shape)

[[[[[1 2 3 4]]]]]
Shape of Array: (1, 1, 1, 1, 4)


## **NumPy Array Reshaping**
## Reshaping arrays


## Reshape From 1-D to 2-D

In [ ]:
# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape From 1-D to 3-D

In [ ]:
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Flattening the arrays


In [ ]:
# Convert the array into a 1D array:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## **NumPy Array Iterating**
## Iterating Arrays


In [ ]:
# Iterate on the elements of the following 1-D array:
import numpy as np

arr = np.array([1,2,3,4,5])
for x in arr:
  print(x)

1
2
3
4
5


## Iterating 2-D Arrays


In [ ]:
# Iterate on the elements of the following 2-D array:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# Iterate on each scalar element of the 2-D array:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays


In [ ]:
# Iterate on the elements of the following 3-D array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [ ]:
# Iterate down to the scalars:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Arrays Using nditer()


## Iterating on Each Scalar Element


In [ ]:
# Iterate through the following 3-D array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Array With Different Data Types


In [ ]:
# Iterate through the array as a string:
import numpy as np

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


## Iterating With Different Step Size


In [ ]:
# Iterate through every scalar element of the 2D array skipping 1 element:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


## Enumerated Iteration Using ndenumerate()


In [ ]:
# Enumerate on following 1D arrays elements:
import numpy as np

arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
# Enumerate on following 2D array's elements:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## **NumPy Joining Array**
## Joining NumPy Arrays


In [ ]:
# Join two arrays:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1):
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Stacking Along Rows


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


## Stacking Along Columns


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth)


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## **NumPy Splitting Array**
## Splitting NumPy Arrays


In [ ]:
# Split the array in 3 parts:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Split the array in 4 parts:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## Split Into Arrays


In [ ]:
# Access the splitted arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


## Splitting 2-D Arrays


In [ ]:
# Split the 2-D array into three 2-D arrays.
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# Split the 2-D array into three 2-D arrays.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# Split the 2-D array into three 2-D arrays along rows.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
# Use the vsplit() method to split the 2-D array into three 2-D arrays along columns.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## **NumPy Searching Arrays**
## Searching Arrays


In [ ]:
# Find the indexes where the value is 4:
import numpy as np

arr = np.array([1,2,3,4,2,4,9,4,5,7])
x = np.where(arr == 4)
print(x)

(array([3, 5, 7]),)


In [ ]:
# Find the indexes where the values are even:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
# Find the indexes where the values are odd:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


## Search Sorted


In [ ]:
# Find the indexes where the value 7 should be inserted:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1




## Search From the Right Side


In [ ]:
# Find the indexes where the value 7 should be inserted, starting from the right:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2




## Multiple Values


In [ ]:
# Find the indexes where the values 2, 4, and 6 should be inserted:
import numpy as np

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


## **NumPy Sorting Arrays**
## Sorting Arrays


In [ ]:
# Sort the array:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
# Sort the array alphabetically:
import numpy as np

arr = np.array(["banana", "cherry", "apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
# Sort a boolean array:
import numpy as np

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


## Sorting a 2-D Array


In [ ]:
# Sort a 2-D array:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
